### ISSUE TITLE
Cannot save any files

### ISSUE THREAD

**Issue by kdoudrick** [USEPA/Environmental-Technologies-Design-Option-Tool#5]
Are there known issues when trying to save files (i.e., save as) on the latest version of Windows 10? I am not able to save any files for any of the programs (e.g., AdOx) - instead the save window pops up but there is no place to enter the file name and when hitting "save" nothing happens.
![image](https://user-images.githubusercontent.com/49442400/93282876-5834c180-f79d-11ea-8b4f-ed2b26c91c4e.png)

*Edit: I discovered a temporary workaround. I name an e.g. temporary file AdOx Temp File.adx and I can actually double click on that and save over the temp file in the Etdot save window. In windows explorer, I can then copy the temp file and rename it whatever I want. So, always keep a temp file available for saving.

**Comment by ucchejbb** [comment]
@kdoudrick Your workaround is similar to the temporary fix I have used of creating a "new notepad document" or "text file" and just renaming it with the appropriate file extension. Then when you save over that, it creates the correct file.
