### ISSUE TITLE
AdDesignS Error #435: ILLEGAL INPUT... INDEX

### ISSUE THREAD

**Issue by Carluna** [USEPA/Environmental-Technologies-Design-Option-Tool#8]
This Error occurs while trying to use AdDesignS with example data ("gas.dat", "liquid.dat") and with user input. My system ist windows 10, 64 bit. I run it under compatibility mode with Win98 and tried all the others. 
Is there a known solution to this issue?
Best regards.

**Comment by ucchejbb** [comment]
@Carluna Unfortunately, the fix to this issue should be to use compatibility mode. You can try setting compatibility mode for the exe's in the folder C:/ETDOT10/ads/exes as well, but that shouldn't be necessary. If you want to provide an email, I can set up a meeting to see if we can diagnose the problem.

**Comment by Carluna** [comment]
@ucchejbb Changing the compatibility mode for the exes doesn't work either. Do you have a public email adress, over which it's possible to contact you?

**Comment by ucchejbb** [comment]
@Carluna Please email me at burkhardt.jonathan@epa.gov

**Comment by Carluna** [comment]
I was able to solve this issue thanks to @ucchejbb! For me it worked to change the operation system language to english (was german before). Now AdDesignS works without any issues.
